$ANSIBLE_VAULT;1.1;AES256
31363562646338393932353439373230313230303638326564393261323137633236343764356234
3331303732626538393332313133636661303063353539650a346434643162666133313334356335
39633037383334323130376265396538623536666565663235653933616636306264336366383735
3934623437333263310a343036626662616439636134666435626664643866303234323537376439
35633638366336636665383631373161363466353234333030396235666664666338303532383735
32656366646134373764316137626239663333376237303966623838343030316266313934663234
38343165326564653834343036643664616131636337376330313530663165343934306538653238
31326632393330316138373965343962333136623130616632396635303763366432623763313764
3966
